apiVersion: v1
kind: Service
metadata:
  name: myfirstservice
  labels:
    name: nginx-srv
spec:
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
    name: http
  selector:
    type: front-node
    app: nginx-app
