apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 80
    nodePort: 30163
    protocol: TCP
    name: http
  selector:
    type: front-node
    app: nginx-app
