apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-svc
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    type: front-node
    app: nginx-app

